Variable scope for Optimizer
Not setting the varibale scope can't ran the optimizer so this error wiil show up:
ValueError: Variable h1_weights already exists, disallowed. Did you mean to set reuse=True in VarScope?